services:
  database:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=just'
      - 'POSTGRES_DB=EcomDB'
      - 'POSTGRES_PASSWORD=pizza'
    volumes:
      - './volumes/postgres:/var/lib/postgresql/data'
